
name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-maliao:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      
      - run: npm run setup
      - run: npm run doc
      - name: deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/plugin-ts-type-doc-demo/dist
      - run: npm install @jsdevtools/npm-publish -g
      - name: deploy packages
        
        run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/plugin-ts-type-doc/package.json

